variable "app_name" {
  type    = string
  default = "checkmk"
}

variable "app_version" {
  type    = string
  default = "2.4.0p2"
}

variable "hcloud_image" {
  type    = string
  default = "ubuntu-24.04"
}

build {
  sources = ["source.hcloud.autogenerated_1"]

  provisioner "shell" {
    inline = ["cloud-init status --wait --long"]
    valid_exit_codes = [0, 2]
  }

  provisioner "file" {
    destination = "/opt/"
    source      = "apps/hetzner/checkmk/files/opt/"
  }

  provisioner "file" {
    destination = "/var/"
    source      = "apps/hetzner/checkmk/files/var/"
  }

  provisioner "shell" {
    environment_vars = ["application_version=${var.app_version}", "DEBIAN_FRONTEND=noninteractive", "LC_ALL=C", "LANG=en_US.UTF-8", "LC_CTYPE=en_US.UTF-8",]
    scripts          = ["apps/shared/scripts/apt-upgrade.sh", "apps/hetzner/checkmk/scripts/install.sh", "apps/shared/scripts/cleanup.sh"]
  }
}
